FROM golang:1.16

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
        npm \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g migrate-mongo

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

ENV GO111MODULE=on

RUN go get github.com/golangci/golangci-lint/cmd/golangci-lint \
    && go get golang.org/x/tools/cmd/goimports

RUN go install github.com/swaggo/swag/cmd/swag@latest

RUN CGO_ENABLED=0
